# This contains all the site specific information (outside of database.yml) that should not be checked into version control.
# It is read in by environment.rb.

#
# It must contain the following fields:
#

##########################
### EMAIL
##########################

# For getting automatic emails when an error occurs
# exception_recipients: List of all emails that should receive the notification
# sender_address: Who the notification email will be from
# email_prefix: What each email should be prefixed with
exception_notifier:
  exception_recipients: "admin@example.com"
  sender_address: '"Application Error" <admin@example.com>'
  email_prefix: "[Typewright] "

# For setting up email - this example uses gmail
smtp_settings:
  address: "smtp.gmail.com"
  port: 587
  domain: 'example.com'
  user_name: 'admin@example.com'
  password: 'super-secret'
  authentication: :plain
  enable_starttls_auto: true
  return_path: http://example.com

##########################
### Skin
##########################

skin:
  title_prefix: 'DEV: '
  edge: false

##########################
### SYSTEM
##########################

paths:
  imagemagick: '/opt/local/bin'
  xml: '~/typewright_xml'

service_settings:
  service_url: 'typewright.tamu.edu'

##########################
### AUTHENTICATION
##########################

authentication:
  private_token: 'super-secret'

##########################
### CAPISTRANO
##########################

capistrano:
  edge:
    user: 'user-name-to-login-to-server'
    ssh_name: 'ssh-name-to-login-to-server'
    ruby: 'ruby-1.9.3-p194'
    deploy_base: '/full/path/to/folder/that/all/web/apps/are/deployed/to'
  production:
    user: 'user-name-to-login-to-server'
    ssh_name: 'ssh-name-to-login-to-server'
    ruby: 'ruby-1.9.3-p194'
    deploy_base: '/full/path/to/folder/that/all/web/apps/are/deployed/to'
 